! Main Program
!
! This program simulates an SIR epidemic process on a population
! structured in households with external contacts generated by
! a configuration model.
!
! Households form fully connected cliques. Some cliques can be
! merged into larger bubbles depending on the number of individuals
! in the household (size): cliques with at most ns members are randomly
! paired and merged. The SIR dynamics is then simulated on the
! resulting network of merged cliques.
!
! OUTPUT:
!   Fraction of recovered individuals in the final epidemic state
!   (conditioned on epidemic outbreaks) in the parameter space
!   (betaI, betaE).
!
! INPUT PARAMETERS:
!   N_nodeI   : total number of individuals in the population
!   nrea      : number of realizations
!   ns        : maximum number of members allowed for household merging
!
!   kminE     : minimum external degree
!   kmaxE     : maximum external degree
!   lambdaE   : parameter of the external degree distribution
!
!   betaI     : transmission probability through internal (household) contacts
!   betaE     : transmission probability through external contacts
!
! INPUT FILES:
!   DistributionPs.dat       : household size distribution P(s)
!   DistributionWorkers.dat  : distribution P(s,w) of households
!                              with size s and w workers
!
!===============================================================

module globals
  implicit none

  integer Smin,Smax,kminE,kmaxE
  integer N_nodeH,N_nodeI
  integer Rtot
  integer tr
  integer dimPGlob

  integer ns

  real(8) lambdaE
  real(8) Smed,kmedE  
  real(8) r  
  real(8) betaE,betai

  integer,allocatable,dimension(:)::HouseholdsSize
  integer,allocatable,dimension(:)::State   
  
  integer,allocatable,dimension(:)::edgepN,nodepN,kkpN,kkiN,kkeN

  integer,allocatable,dimension(:)::edgep
  integer,allocatable,dimension(:)::nodep
  integer,allocatable,dimension(:)::kkp,kki,kke
  integer,allocatable,dimension(:)::kkC,nWorkersH
  integer,allocatable,dimension(:)::Svec,Ivec
  
  real(8),allocatable,dimension(:)::Pss,PkE
  real(8),allocatable,dimension(:,:)::Supp,PinfRec  
  real(8),allocatable,dimension(:,:)::PswDistr
    
end module globals

module random
   integer::q1=1,q2=104
   integer ir(670)
   integer::sem(670)
   real(8)::nmax=2*(2**30-1)+1
   real(8) sig
end module random


Program MainProgram
  use globals
  use random

  implicit none

  integer i,j,rea,nrea,ni,ne
  integer zz
  integer Aux,scc
  integer AuxI1,AuxI2
  integer nptosI,nptose
  real(8) product1,product2,Aux1,Aux2
  real(8) AuxR1
  real(8),allocatable,dimension(:)::Factor
  real(8),allocatable,dimension(:)::betaEfrac,betaIfrac
  
  character(8) Var01
  character(3) Var02
  character(4) Var03
  character(4) Var04
  character(3) Var05
  character(5) Var06

  call initialize_random
  
  !Parameters

  N_nodeI=500000                  !number of individuals
  scc    =N_nodeI*0.5d0/100d0    !minimum number of recovered individuals required to classigy a realization as an epidemic
  nrea   =400                   !total number of realizations
  ns     =1                      !maximum household size to be merge
  tr     =1                      !recovery time
    
  kminE  =1    !minimum external degree
  kmaxE  =5    !maximum external degree
  lambdaE=2d0  !parameter of the external degree distribution
  
  

  
  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  ! Read the household size distribution P(s) from file  
  
  nptosI =100
  nptosE =100

  zz     =0
  open(1,file="DistributionPs.dat")
  do 
     read(1,*,end=7) AuxI1,AuxR1
     zz   =zz+1
  enddo
7 rewind(1)
  Smin  =1
  Smax  =AuxI1
  allocate(Pss(Smin:Smax))
  Pss   =0d0
  do i=1,zz
     read(1,*) AuxI1,AuxR1
     Pss(AuxI1)=AuxR1
  enddo
  Pss  =Pss/sum(Pss)
  Smed=0d0
  do i=Smin,Smax
     Smed=Smed+i*Pss(i)
  enddo   
  close(1)


  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  ! Read the distribution P(s,w): fraction of households of size s with w workers.
  ! Column 1: household size s
  ! Column 2: number of workers w
  ! Column 3: fraction of households with size s and w workers
  allocate(PswDistr(0:Smax,Smin-1:Smax))
  PswDistr  =0d0
  zz        =0
  open(1,file="DistributionWorkers.dat")
  do 
     read(1,*,end=8)
     zz =zz+1   
  enddo
8 rewind(1)
  do i=1,zz
     read(1,*) AuxI1,AuxI2,AuxR1
     PswDistr(AuxI1,AuxI2)=AuxR1  
  enddo
  close(1)
  



  write(Var01,'(I8)') N_nodeI
  call zeros(Var01)
  write(Var05,'(I3)') ns
  call zeros(Var05)


  allocate(PkE(kminE:kmaxE))
  allocate(Svec(0:N_nodeI),Ivec(0:N_nodeI))
  allocate(Factor(0:20))
  allocate(betaEfrac(nptosE),betaIfrac(nptosI))
  
  
  do i=1,nptosE
     betaEfrac(i)=0.01d0*i
  enddo
  do i=1,nptosI
     betaIfrac(i)=0.01d0*i
  enddo
  
  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  
  !External degree probability distribution
  Factor        =0d0
  Factor(0)     =1d0
  do i=1,20
     Factor(i)=Factor(i-1)*i
  enddo    
  !Degree distribution Individuals
  PkE           =0d0
  
  
  do i=kminE,kmaxE
     PkE(i)=exp(-lambdaE)*lambdaE**(i)/Factor(i)
  enddo  
  PkE  =PkE/sum(PkE)
     
  kmedE=0d0
  do i=kminE,kmaxE
     kmedE=kmedE+i*PkE(i)
  enddo
  
  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

  allocate(kkp(N_nodeI),kke(N_nodeI),kki(N_nodeI),nodep(N_nodeI))  
  allocate(HouseholdsSize(N_nodeI))
  allocate(nodepN(N_nodeI),kkpN(N_nodeI),kkiN(N_nodeI),kkeN(N_nodeI))
  allocate(State(N_nodeI))
 
  allocate(Supp(nptosI,nptose),PinfRec(nptosI,nptose))
  rea   =0

  Supp          =0
  PinfRec       =0

  do while(rea<nrea)     
     rea=rea+1
     print*,rea
     open(1,file="realization.dat")
     write(1,*) rea
     close(1)
     call ConfModel  
     call Merge
     
     doafuera:do ni=1,nptosI
        betaI  =betaIfrac(ni)
        doAdentro:do ne=1,nptosE
           betaE=betaEfrac(ne)
           call SIR         
           if(Rtot>scc)then
              Supp(ni,ne)        =Supp(ni,ne)+1    
              PinfRec(ni,ne)     =PinfRec(ni,ne)+Rtot
           endif
        enddo doAdentro
     enddo doafuera     

     open(2,file='tot_recov_NI_'//Var01//'_ns_'//Var05//'.dat')
     do ni=1,nptosI
        do ne=1,nptosE
           if(Supp(ni,ne)>0)then
              write(2,*)betaIfrac(ni),betaEfrac(ne),PinfRec(ni,ne)/Supp(ni,ne)/N_nodeI
           else
              write(2,*)betaIfrac(ni),betaEfrac(ne),0d0
           endif
        enddo
     enddo

     close(2)

     
     deallocate(edgep,edgepN,nWorkersH)          
  enddo

end Program MainProgram

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!
!!!   SIR
!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

subroutine SIR
  use globals
  use random
  implicit none
  integer i,j
  integer sel,nod,vec
  integer Nindex,Nremanent,Aux,Aux1
  integer Ninf,NinfAux,NisoInew
  integer tt,Ntot,Nsus
  integer, dimension(N_nodeI):: ListIndInf,ListIndRec
  integer, dimension(N_nodeI):: ListIndInfNew,ListIndRecNew
  integer, dimension(N_nodeI):: ListSel,Clock

  
  !State=0  :susceptible
  !State=1  :infected
  !State=2  :Recovered
  
  Ivec          =0
  Svec          =N_nodeI
  
  State         =0
  Ninf          =0   !number of infected individuals

  ListIndInf    =0   !List of infected individuals
  ListIndRec    =0   !List of recovered individuals


  Rtot          =0   !number of individuals ever infected
  tt            =0

  ListSel       =0
  do i=1,N_nodeI
     ListSel(i)=i
  enddo


  
  !INDEX-CASES
  Nremanent     =N_nodeI
  Nindex        =1
  Clock         =0
  do i=1,Nindex
     call rand
     sel =r*Nremanent+1
     Aux =ListSel(sel)
     State(Aux)=1
     Ninf =Ninf+1     
     ListIndInf(Ninf) =Aux     

     ListSel(sel)=ListSel(Nremanent)
     Nremanent=Nremanent-1
  enddo
  Aux1=1

  do while(Ninf>0)
     !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
     !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
     !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
     !New time step
     tt    =tt+1
     !STEP 1: TRANSMISSION
     NinfAux       =0
     ListIndInfNew =0

     do i=1,Ninf
        nod       =ListIndInf(i)
        Clock(nod)=Clock(nod)+1                       
        do j=1,kkp(nod)
           vec =edgep(nodep(nod)+j-1)
           call rand
           
           if(j<=kki(nod))then
              if(r>betaI)cycle
           else           
              if(r>betaE)cycle
           endif
           
           if(State(vec)==0)then
              State(vec)  =1
              NinfAux     =NinfAux+1              
              ListIndInfNew(NinfAux)=vec   
              Aux1        =Aux1+1           
           endif
        enddo      
     enddo
         
     
     !STEP 3: RECOVER
     !Those individuals who have been infected for tr time steps, will now 
     !move to the recovered compartment
     
     
     do i=1,Ninf
        nod      =ListIndInf(i)
        if(Clock(nod)<tr)then
           NinfAux  =NinfAux+1
           ListIndInfNew(NinfAux)=nod
        else
           State(nod)=2
           Rtot      =Rtot+1  
        endif
     enddo  
     
     Ninf=NinfAux           
     ListIndInf=ListIndInfNew

  enddo 


end subroutine SIR


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!
!!!   Configuration Model
!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!This subroutine creates three arrays: kkp, edgep, and nodep, which contain all the network topology information.
!kkp(i) is the total degree of node "i".
!The subset edgep(nodep(i):nodep(i)+kkp(i)-1) contains the list of neighbors of node "i".

subroutine ConfModel
  use globals
  use random
  implicit none
  integer i,j,k,ll
  integer nod1,nod2,vec,popul,sel
  integer Aux,AuxH,AuxA,AuxA1,AuxA2,flag
  integer m,n
  integer counting,nstubsE
  integer nstubAux,stubpos1,stubpos2
  integer mayor,menor

  real(8) ws

  integer, allocatable, dimension(:)::listStubE,kkAux,WorkerYesNo  

  real(8),dimension(Smin-1:Smax)::CumulativePss  
  real(8),dimension(kminE-1:kmaxE)::CumulativePkE
  
  real(8),dimension(Smin:Smax,-1:Smax)::CumulativePsw
    
  allocate(kkAux(N_nodeI),WorkerYesNo(N_nodeI))

  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  !!Cumulative distribution Household Size
  
  CumulativePss  =0d0
  ws             =0d0
  do i=Smin,Smax
     ws                 = ws+Pss(i)
     CumulativePss(i)   = ws
  enddo

  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  !!Cumulative distribution of workers per household
  CumulativePsw  =0d0  
  do i=Smin,Smax
     ws   =0d0
     do j=Smin,Smax
        ws                  = ws+PswDistr(i,j)
        CumulativePsw(i,j)  = ws
     enddo
  enddo
  
  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  !!Cumulative distribution External Degree
  
  CumulativePkE  =0d0
  ws             =0d0
  do i=kminE,kmaxE
     ws                 = ws+PkE(i)
     CumulativePkE(i)   = ws
  enddo  
  
  
  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  !!Assignment of household sizes
2 kkp=0 
  HouseholdsSize=0
  N_nodeH=0
  popul    =0
  do i=1,N_nodeI
     call rand
     do j=Smin,Smax
        if(CumulativePss(j-1)<r.and.r<=CumulativePss(j)) then          
           if(popul+j<=N_nodeI)then
              HouseholdsSize(i)    =j
              N_nodeH              =N_nodeH+1
              popul                  =popul+j
              if(popul==N_nodeI)goto 33
              exit
           else
              HouseholdsSize(i)    =N_nodeI-popul
              N_nodeH              =N_nodeH+1
              goto 33
           endif           
        endif
     enddo
  enddo
  
33 Aux=0
  kki =0
  kke =0
  allocate(nWorkersH(N_nodeH))
  nWorkersH  =0
  do i=1,N_nodeH
     AuxH  =HouseholdsSize(i)
     do j=1,AuxH
        Aux  =Aux+1
        kki(Aux)=AuxH-1     !internal degree within the household
     enddo
     !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
     !Assign number of workers in the household
     call rand
     do j=0,Smax
        if(CumulativePsw(AuxH,j-1)<r.and.r<=CumulativePsw(AuxH,j))then
           nWorkersH(i)    =j
        endif
     enddo
  enddo
  
  !Randomly select workers within each household
  WorkerYesNo =0
  popul       =0 
  do i=1,N_nodeH
     AuxH  =HouseholdsSize(i)
     do j=1,nWorkersH(i)
44      call rand
        sel =r*AuxH+popul+1
        if(WorkerYesNo(sel)==0)then
           WorkerYesNo(sel) =1
        else
           goto 44
        endif
     enddo
     popul=popul+AuxH
  enddo


  !Assign external degree to workers
  do i=1,N_nodeI
     if(WorkerYesNo(i)==0)cycle
     call rand
     do j=kminE,kmaxE
        if(CumulativePkE(j-1)<r.and.r<=CumulativePkE(j)) then
           kke(i)    = j
           exit
        endif
     enddo
  enddo  
  
  if(mod(sum(kke),2)/=0)then
     do
        call rand
        sel  =N_nodeI*r+1
        if(kke(sel)>1)then
           kke(sel)=kke(sel)-1
           exit
        endif     
     enddo
  endif
  

  nstubsE =sum(kke)  

  kkp     =kki+kke
  
  nodep(1)=1
  do i=2,N_nodeI
     nodep(i)=nodep(i-1)+kkp(i-1)
  enddo
  
  allocate(listStubE(nstubsE))  
  allocate(edgep(sum(kkp)))
  
  kkAux         =0
  edgep         =0
  AuxA1         =1
  AuxA2         =HouseholdsSize(1)
  !Fill edgep with internal household connections
  do i=1,N_nodeH
     AuxH  =HouseholdsSize(i)
     if(AuxH==1)then
        if(i<N_nodeH)then
           AuxA1=AuxA2+1
           AuxA2=AuxA2+HouseholdsSize(i+1)        
        endif
        cycle
     endif
     do j=AuxA1,AuxA2
        do k=j+1,AuxA2
           edgep(nodep(j)+kkAux(j))=k
           edgep(nodep(k)+kkAux(k))=j
           kkAux(j)  =kkAux(j)+1
           kkAux(k)  =kkAux(k)+1
        enddo
     enddo
     if(i<N_nodeH)then
        AuxA1=AuxA2+1
        AuxA2=AuxA2+HouseholdsSize(i+1)
     endif
  enddo
  

  listStubE     =0
  nstubAux      =0

  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  !!List of stubs

  do i=1,N_nodeI
     if(kke(i)==0) cycle
     do k=1,kke(i)
        nstubAux           =nstubAux+1
        listStubE(nstubAux)=i
     enddo
  enddo
  
  !Construction of external links
  counting    =0
  do while(nstubsE>0)
3    if(counting==100) then
	deallocate(listStubE,edgep,nWorkersH)
	go to 2
     end if
     
     !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
     !!Randomly choose two external stubs
     
     call rand
     stubpos1    =r*nstubsE+1
     call rand
     stubpos2    =r*nstubsE+1

     m        =listStubE(stubpos1)   !the first stub corresponds to node "m"
     n        =listStubE(stubpos2)   !the second stub corresponds to node "n"

     !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
     !!Checking whether these two stubs can be joined or not

     if(m.ne.n) then
	do k=1,kkAux(m)
           if(edgep(nodep(m)+k-1)==n)then
              counting     =counting+1
              go to 3   !if nodes "m" and "n" are already consected, we have to choose another pair of stubs
           endif
	enddo
	edgep(nodep(m)+kkAux(m))   =n
	edgep(nodep(n)+kkAux(n))   =m

	kkAux(m)                 =kkAux(m)+1
	kkAux(n)                 =kkAux(n)+1
	
	mayor=max0(stubpos1,stubpos2)
	menor=min0(stubpos1,stubpos2)	

	if(mayor==nstubsE) then
		listStubE(mayor)=listStubE(nstubsE)
		listStubE(menor)=listStubE(nstubsE-1)
	else 
		if (mayor==nstubsE-1) then
		listStubE(menor)=listStubE(nstubsE)
		else
		listStubE(mayor)=listStubE(nstubsE)
		listStubE(menor)=listStubE(nstubsE-1)
	        endif
	endif
	
	nstubsE             =nstubsE-2
	counting            =0
     else
        counting           =counting+1
        go to 3 !self-loops are forbidden
     endif
  enddo
  
  kkp  =kkAux
  
  
  deallocate(kkAux,listStubE)
  
  
end subroutine ConfModel

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!
!!!   Merging households
!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
subroutine Merge
  use globals
  use random
  implicit none
  integer i,j,k,ContC
  integer Aux1,Aux2,LC,C1,C2,p1,p2
  integer n1,n2
  integer flag
  integer, dimension(N_nodeH)::nodeC
  integer, dimension(N_nodeH)::ListC,ListHead,ListTail,SelectedOrNot
  integer, dimension(N_nodeI)::kkn,kkAux
  
  integer,allocatable,dimension(:)::ListMembers
  
  ListHead=0
  ListTail=0
  
  ListC   =0
  ContC   =0
  SelectedOrNot =0
  !Households eligible for merging
  do i=1,N_nodeH
     if(HouseholdsSize(i)<=ns)then
        ContC        =ContC+1
        ListC(ContC) =i
     endif
  enddo
  !List household members
  nodeC   =0
  allocate(ListMembers(sum(HouseholdsSize)))
  ListMembers   =0
  nodeC(1)      =1
  do i=2,N_nodeH
     nodeC(i)=nodeC(i-1)+HouseholdsSize(i-1)
  enddo
  Aux1   =0
  do i=1,N_nodeH
     do j=1,HouseholdsSize(i)
        Aux1              =Aux1+1
        ListMembers(nodeC(i)+j-1)=Aux1
     enddo    
  enddo  


  LC      =0
  kkn     =0
  kkiN    =0
  kkeN    =0
  do j=1,ContC
     C1 =ListC(j) 
     if(SelectedOrNot(C1)==1)cycle  
     LC            =LC+1
     ListHead(LC)  =C1
     SelectedOrNot(C1)   =1
     
78   call rand
     C2   =r*N_nodeH+1
     if(SelectedOrNot(C2)==1.or.HouseholdsSize(C2)<=ns)goto 78
     ListTail(LC)  =C2
     SelectedOrNot(C2)   =1
     
     do i=1,HouseholdsSize(C1)
        n1      =ListMembers(nodeC(C1)+i-1)
        kkn(n1) =HouseholdsSize(C2)
     enddo
     
     do i=1,HouseholdsSize(C2)
        n2      =ListMembers(nodeC(C2)+i-1)
        kkn(n2) =HouseholdsSize(C1)
     enddo
  enddo
  dimPGlob  =sum(kkp+kkn)
  allocate(edgepN(dimPGlob))
  edgepN=0
  nodepN(1) =1
  do i=2,N_nodeI
     nodepN(i) =nodepN(i-1)+kkp(i-1)+kkn(i-1)     
  enddo
  
  kkAux     =0
  
  !Start merging process: add new internal neighbors
  do i=1,LC
     C1   =ListHead(i)
     C2   =ListTail(i)
     
     do j=1,HouseholdsSize(C1)
        n1  =ListMembers(nodeC(C1)+j-1)
        kkAux(n1) =HouseholdsSize(C2)
        kkiN(n1)  =kkAux(n1)
        edgepN(nodepN(n1):nodepN(n1)+kkAux(n1)-1)  =ListMembers(nodeC(C2):nodeC(C2)+kkAux(n1)-1)
     enddo
     do j=1,HouseholdsSize(C2)
        n2  =ListMembers(nodeC(C2)+j-1)
        kkAux(n2) =HouseholdsSize(C1)
        kkiN(n2)  =kkAux(n2)
        edgepN(nodepN(n2):nodepN(n2)+kkAux(n2)-1)  =ListMembers(nodeC(C1):nodeC(C1)+kkAux(n2)-1)     
     enddo     
  enddo
  
  !Add the remaining connections to the new adjacency list
  !We have to check whether two nodes from different cliques to be merged were already connected via an external link
  !If they were already connected, the external link becomes internal
  do i=1,N_nodeI
     !Add pre-existing internal neighbors
     do j=1,kki(i)
        n1  =edgep(nodep(i)+j-1)
        edgepN(nodepN(i)+kkiN(i)+j-1)=n1
     enddo
     
     kkiN(i)  =kkiN(i)+kki(i)
     !Add external neighbors
     Aux2=0
     do j=1,kke(i)
        n1  =edgep(nodep(i)+kki(i)+j-1)
        flag=0
        do k=1,kkiN(i)
           if(edgepN(nodepN(i)+k-1)==n1)then
              flag=1
              exit
           endif
        enddo
        if(flag==0)then
           edgepN(nodepN(i)+kkiN(i)+Aux2)=n1
           Aux2=Aux2+1
        endif
     enddo      
     kkAux(i) =kkiN(i)+Aux2
     kkeN(i)  =Aux2

  enddo
  
  kkpN   =kkAux
  
  deallocate(edgep)
  allocate(edgep(dimPGlob))
  edgep  =edgepN
  kkp    =kkpN
  kki    =kkiN
  kke    =kkeN
  nodep  =nodepN
  
end subroutine Merge



!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!
!!!   Seed for the Pseudorandom number generator
!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
subroutine initialize_random
  use globals
  use random
  implicit none

  integer i,see(33)
  integer hour

  CALL SYSTEM_CLOCK(hour)
  print*,'seed',hour
  !hour=537838959
  
  see=hour
  CALL RANDOM_SEED(put=see)		
  CALL RANDOM_SEED(get=see)

  do i=1,670
     call random_number(r)
     sem(i)   =r*nmax
     ir(i)    =i+1
  enddo
  ir(670)=1
  return
end subroutine initialize_random
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!
!!!   Pseudo-random number generator
!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
subroutine rand
  use globals
  use random
  implicit none

 1 q1=ir(q1)
  q2=ir(q2)
  sem(q1)= IEOR(sem(q1),sem(q2))
  r=dfloat(sem(q1))/nmax
  if(r==1d0.or.r==0d0) go to 1
  return
end subroutine rand


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!
!!!   Zero Character
!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

subroutine zeros(b)
 implicit none
 
 character(*):: b
 integer i
 
 do i=1,len(b)
   if (b(i:i)==' ') then  
      b(i:i)='0'
   endif
 end do
end subroutine zeros


